# Generated by Django 5.0.6 on 2024-07-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="uid",
            field=models.CharField(default=1, max_length=24, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
