# Generated by Django 5.0.6 on 2024-07-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_event_uid_event_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="uid",
            field=models.CharField(max_length=24, null=True, unique=True),
        ),
    ]
